### ISSUE TITLE
Non-IOExceptions are not well handled in RestxRoutes

### ISSUE THREAD

**Issue by fcamblor** [restx/restx#121]
If a `RestxResource` endpoint throws an exception which doesn't inherit form `IOException`, generated code doesn't handle well these types of exception.

Looking at the source code, we have `IOException` in all the call hierarchy, which would make the change complicated on the api side.

Workaround would then be to generate a `try/catch` block in the Router generated code.
Something like this :

```
            protected Optional<my.package.domain.MyPojo> doRoute(RestxRequest request, RestxRequestMatch match, Void body) throws IOException {
                securityManager.check(request, open());
                try {
                    return Optional.of(resource.myEndpoint());
                } catch(/* Present only if myEndpoint throws IOException -> */ IOException | RuntimeException e){
                    throw e; // Re-throwing initial IOException/RuntimeException
                } catch(Exception e){
                    // Encapsulating checked exception into a RuntimeException
                    throw new RuntimeException(e);
                }
             }
```

WDYT ?

**Comment by xhanin** [comment]
I realize I never gave my opinion on that, I'm obviously fine with that, no problem for me. The only downside I see is that developers will then see an exception thrown from generated code, and some developers don't go to check the `caused by` section and will get lost. So we should better throw our own exception rather than RuntimeException (sg like `WrappedCheckedException`), and catch it specifically in `StdRestxMainRouter` to "display" the original exception rather than the wrapper one.

WDYT?

**Comment by dadoonet** [comment]
@xhanin I agree with your proposal. It looks good to me.
