### ISSUE TITLE
How to limit an account only one user at the same time online？

### ISSUE THREAD

**Issue by Dreampie** [restx/restx#147]

**Comment by fcamblor** [comment]
Hi Dreampie,

I think such questions should be asked on the [mailing list](https://groups.google.com/forum/#!forum/restx) rather than on the issue tracker.

Not saying we cannot create discussions in the issue tracker, but it should be dedicated to discussions about bugs or new features.

By asking something in the issue tracker, you will only reach restx commiters, whereas asking in the google group, the entire community will be aware of your problem and will be able to answer it.

Returning to your question, to my POV, this is not the restx responsibility to handle this case : this is rather a "business" question you should handle yourself.
It brings lots of questions : what is an account ? a User ? What means "at the same time" ?
A way of implementing this would be to persist `Session` instances and restrict only 1 `Session` opened for a given user in a given time lapse (for instance, in a x minutes window), not allowing to create a new `Session` if the same user has already opened one in the latest x minutes.

I'll close your issue here, if you want to discuss it, please discuss it on the mailing list.
Thanks

**Comment by Dreampie** [comment]
Hi, my friend, in Chinese access to certain Google service is not convenient, must use a proxy, such as: goagent, so I have to use GitHub,I'm sorry.
