### ISSUE TITLE
HotCompile issue

### ISSUE THREAD

**Issue by ltouati** [restx/restx#157]
Hi There,

First thanks for this great framework you've built. 

I'm having however an issue that is quite annoying specially when running in dev mode. Quite often on my services I have the following error message

  QueryByName{name=Name{name='RestxRouting', clazz=restx.RestxRouting[AppClassLoader]}}
    |       \__=> Name{name='RestxRouting', clazz=restx.RestxRouting[AppClassLoader]}
    |
    +-> QueryByClass{componentClass=restx.RestxRouter[AppClassLoader]}
      |       \__=> Name{name='RegistrationResourceRouter', clazz=com.chictypes.services.registration.rest.RegistrationResourceRouter[HotCompile[2]]}
      |
      +-> QueryByClass{componentClass=com.chictypes.services.registration.rest.RegistrationResource[HotCompile[2]]}
        |       \__=> Name{name='RegistrationResource', clazz=com.chictypes.services.registration.rest.RegistrationResource[HotCompile[2]]}
        |
        +-> QueryByClass{componentClass=com.chictypes.services.registration.components.LoadBalancerService[HotCompile[2]]}
              |
              +--: component satisfying QueryByClass{componentClass=com.chictypes.services.registration.components.LoadBalancerService[HotCompile[2]]} not found.

com.chictypes.services.registration.components.LoadBalancerService is an interface implemented by a component. 

It works perfectly in production mode and hence seems to be linked to the hot compilation.

I'm running restx 0.33.1

Any idea on how to fix this ?

Thx

**Comment by xhanin** [comment]
HotCompile has some tricky issues due to the way it has to work with classloaders.

The kind of problem you face is usually due to a class being loaded by 2 separate classloaders, here I think you get the component implementing this interface loaded by the initial classloader (it it is `AutoStartable` or an `AutoStartable` component has a dependency on it) so the component is available as implementing your `LoadBalancerService` interface but as defined by the initial classloader, and then your registration resource which is hot loaded tries to have the `LoadBalancerService` injected but with the interface defined in the hot compile classloader.

RESTX usually tries to mark the classes used in `AutoStartable` components as cold classes (which are not hot compiled) in this piece of code:
https://github.com/restx/restx/blob/master/restx-core/src/main/java/restx/RestxMainRouterFactory.java#L694

I guess the problem here is that your implementation is marked as a cold class, but not the interface itself.

Sadly the current implementation does not allow to configure cold classes manually, and use the actual class of your component to mark it as cold class, so you have no way to trick it at this stage.

So currently the workaround is to either:
- don't use hotcompile :(
- move `LoadBalancerService` outside the package defined as `restx.app.package`
- change your `restx.app.package` setting to a package which does not include `LoadBalancerService`, and then only that package will be hot compiled

OTOH I suggest to open 2 enhancements:
- allow to configure a list of cold packages
- auto mark as cold classes the full inheritance tree of classes loaded  by initial classloader

**Comment by a-peyrard** [comment]
I totally agree for the two enhancements, it's really not convenient to reorganise sources in order to make hot-reload work.

**Comment by ltouati** [comment]
Hi Guys,

It was indeed due to the fact this class was called in an autostartable
block. I've reorganized my code and it works. However I can't wait for this
enhancement to be ready.

Any way I can help ?

I have one other question also, is there a simple way to create a self
running jar. My idea is to run all the services in docker images, and the
way restx is packaged makes it very complicated.

Thx again

Le Fri Feb 13 2015 at 13:51:57, a-peyrard <notifications@github.com> a
écrit :

**Comment by fcamblor** [comment]
I'd prefer to talk about these questions [on the google group](https://groups.google.com/forum/#!forum/restx).
Unfortunately, github doesn't share you email so I didn't achieve to fork the discussion on ggroup :-)

Concerning the self running jar topic in docker image, you have several options :
- The most reliable (at the moment) is to make an "uber jar" at packaging time, using something like [onejar-maven-plugin](https://code.google.com/p/onejar-maven-plugin/)
In that case, no pre-requisite is required
- You can use the `restx app grab <coordinates> + app run` command where `coordinates` should be a git repository url (specific hash/tag can be appended like `#<ref>` after the git url)
In that case, you will need a docker image with `restx shell` installed on it. The best one available in the wild (which I know of) is [@ggtools's one](https://github.com/ggtools/restx-docker)

**Comment by a-peyrard** [comment]
PR #175 fix the cold classes issue
