### ISSUE TITLE
Add to ConfigLoader the capability to load properties files from the file system

### ISSUE THREAD

**Issue by a-peyrard** [restx/restx#158]
Currently only resources from the classpath can be loaded, it might be nice to allow to load files from the file system.

WDYT ?

**Comment by fcamblor** [comment]
Wondering if this is a good idea, because it opens doors to unwanted things :
- deploying a restx-packaged app (`restx app grab http://path/to/myapp-restx.jar + app run`) with filesystem dependent paths won't work (no self-sufficient archive anymore) unless you provide it at runtime
- I personnaly consider targeting some filesystem-related stuff was not a good practice in software dev

*but* OTOH, I know having a self-sufficient archive may lead to some security issues (packaging clear passwords in the archive for every envs, including production, may be considered a security issue ... and a solution would be to let ops define their own environment properties from external application properties, through filesystem properties).

So, I'll +0 for this :-)

**Comment by a-peyrard** [comment]
I agree with all you point, cons and pros ;)

Having properties outside the package might also ease changes, especially when credentials for a database or any other third party system is changed.
But having resources loaded from classpath does not mean we have to package those properties in the application archive. So I don't find any use case where I really need to access a property file. 
Currently I'm working on a shell at work, and I use properties to provide something like a "rc" file, but I don't think I need the "env" management that is done in `ConfigLoader`, so I can live with my code (which is using directly a `StdRestxConfig`).

So I propose that we leave the subject for a while till we find any real use case.

**Comment by xhanin** [comment]
I've just created #186 which is a partial duplicate of this one (wasn't remembering that discussion when I created it). We have the use case where people prefer to have their settings on the filesystem rather than packaged in the app (which has some advantages in terms of release management), and the way to achieve it by putting the settings in the server classpath is not very convenient. Moreover it's very easy to implement (at least what is described in #186) so I'll go for it.

While doing it I can also add a method to load settings from a `Path` in config loader, that's just adding flexibility at the API level, people will see if they want to use it or not.
