### ISSUE TITLE
Autocompile duplicates resources on the classpath (workaround included)

### ISSUE THREAD

**Issue by cpo** [restx/restx#178]
Consider this project structure:

```
pom.xml
  +--- src/main/resources/liquibase.xml 
```

My usecase is running it from intellij idea with maven integration enabled, running restx in development mode.

Compiling through maven will output the classes to target/classes, so the liquibase.xml file ends up under target/classes/liquibase.xml

When the autocompiler kicks in, a new output directory called target/restx will be created, with all the resources under src/main/resources included again. The running process now has all the resources duplicated in the class loader. 

This is something liquibase will not appreciate, resulting in errors that it can find the liquibase.xml multiple times.

The workaround is to change the maven output directory in the pom:

```
    <build>
        <outputDirectory>target/restx/classes</outputDirectory>
    </build>
```

But it would be nice to change the autocompiler to respect the maven output directory or to easily change the output directory of the autocompiler.

Besides this small issue: a really impressive product!

**Comment by xhanin** [comment]
Actually we use a different target directory to avoid collisions between the IDE / maven compilation and RESTX one. It's not that I have really a bad experience with using the same destination, it's more that I fear it could raise problems, especially depending on how the IDE is setup.

But I understand that it causes problems, it's just that I'm not sure of how we should address it. Currently you can override restx output directory with `restx.targetClasses` system property. So there is also the workaround to set that instead of changing your maven settings. Maybe properly documenting that would be enough?

What do you think?

**Comment by cpo** [comment]
Sounds sane! I could not find it in the documentation so mentioning it would be nice :+1:
