### ISSUE TITLE
Compilation Manager attemps to compile .swp files

### ISSUE THREAD

**Issue by Inphi** [restx/restx#243]
I frequently use vim to edit java files, and vim generates .swp files under 'src' upon an edit of the underlying.
Is there a way to configure the restx-classloader to ignore certain files, or at least ignore dotfiles?

**Comment by fcamblor** [comment]
Are you really encountering compilation errors on .swp files ?
Could you give use more logs ?

Because looking at the source, only `*.java` files [are compiled](https://github.com/restx/restx/blob/be01892571b8d6b3bff04cc7b58152fd23192763/restx-classloader/src/main/java/restx/classloader/CompilationManager.java#L335) (others are simply copied)

**Comment by Inphi** [comment]
This is the log i'm getting (with level="DEBUG" for restx.classloader.CompilationManager)
```2016-02-29 15:34:24,276 [pool-4-thread-1 ] [          ] INFO  restx.classloader.CompilationManager - classpath resource updated: com/example/utils/.FooUtils.java.swp```

I'm not getting any visible errors on the .swp files, and my program runs as expected regardless.

**Comment by fcamblor** [comment]
No problems here, we're only notifying the resource has been updated (and thus, has been copied in `classes` directory, alongside other compiled classes / ressources)

Looks fine for me
