### ISSUE TITLE
Allow to define which main dependency provisioner is used through md.restx.json property

### ISSUE THREAD

**Issue by fcamblor** [restx/restx#250]
Currently, if we're using maven as our main build tool, we need to have an `ivy.xml` file to make commands such as `restx deps install` or `restx app run` (which is based on installed deps) to work properly.

As most of developper have a better knowledge of maven than ivy, it would be interesting to make mandatory the tracking of dependencies updates in 2 different places.

For this, I would suggest to add a `md.restx.json` entry stating if we're on an `ivy` or a `maven` dependency provisionner tool.
Something like :

```
{
    "module": "foo.bar:quix:0.1-SNAPSHOT",
    "packaging": "war",
    "provisionDepsWith": "maven",
    ....
}
```

This property would be taken into consideration when :
- We call `restx deps install` : if "ivy", we would keep current behaviour, and if "maven", we would make a `mvn dependency:copy-dependencies -DoutputDirectory=${appSettings.targetDependency()} -DexcludeScope=test`
- We `restx build generate` (would be another way to implement #172)
- We `restx deps add`

**Comment by xhanin** [comment]
`ivy.xml` is not what is used, it's the `md.restx.json` file which is used, using Ivy API under the hood indeed.

I wouldn't put a property in the md.restx.json file, because it is misleading: you keep that file mainly to indicate that you use Maven, but then you don't trust it for the dependencies declaration.

What I would do is:
1) during `restx app new`, allow to choose which dependency descriptors you want: 
- `md.restx.json` only
- `md.restx.json` + `ivy.xml`
- `md.restx.json` + `pom.xml`
- `md.restx.json` + `ivy.xml` + `pom.xml`
- `pom.xml` only
- `ivy.xml` only

The first 4 options are what is available today, the 2 last ones are new.

2) during `restx deps install`, do the following:
- if `md.restx.json` file is present, use it (current behaviour)
- if `pom.xml` file is present, use `mvn dependency:copy-dependencies -DoutputDirectory=${appSettings.targetDependency()} -DexcludeScope=test`
- if `ivy.xml` file is present, use it with Ivy API embedded in `restx`

In the first case, we could also internally parse the `pom.xml` file (if present) and.or the `ivy.xml` file (if present), and detect if the dependencies are not in sync with `md.restx.json` file (with a simple comparison) and then either warn, fail or propose to autofix by merging.

3) see if we can handle `restx deps add` properly
