### ISSUE TITLE
RestX console and urlencode of path params

### ISSUE THREAD

**Issue by Mathieu-Castets** [restx/restx#257]
![capture d ecran 2017-02-21 a 17 05 20](https://cloud.githubusercontent.com/assets/4427447/23173556/d368584a-f859-11e6-89a4-9844544d26fc.png)

I would like to test one endpoint which expects an ISO-format date in the path. It works as expected when using postman or RESTClient but fails when using the restx console.

I think we should not urlencode path parameters or, if this is breaking or raise a security issue, not urlencode path parameter of date datatype.

**Comment by fcamblor** [comment]
I'm not sure about what to do here, there are 2 options :

Option 1 : don't `urlencode()` PATH parameters [when sending it through RestX Console](https://github.com/restx/restx/blob/master/restx-apidocs/src/main/resources/restx/apidocs/js/controllers/OperationController.js#L55)

Option 2 : url decoding path parameters [when creating path params map](https://github.com/restx/restx/blob/master/restx-core/src/main/java/restx/StdRestxRequestMatcher.java#L52)

Option 2 is a breaking change (if you actually have `%` characters in your path parameters, they will be interpolated when parsed), which makes me feel like it is not a good idea.

I would rather be in favour of Option 1, will make a PR in this direction.

**Comment by xhanin** [comment]
I'm not sure the Option 2 isn't better, but it indeed is a major breaking change. To be honest when I first implemented the `RestxRequest` interface I was thinking it should be part of its job to decode the url encoded parameters. But in the implementation, especially the servlet based one, I assumed the servlet API was doing so, and we still have this flaw years after, so that I know several people using `String` parameters in restx resource methods to url decode them manually and then convert them in the appropriate type. So maybe we could take advantage of a new release to fix this behavior (aka Option 2), and have a setting to configure restx to behave in compatibility mode (because it's a major breaking change). 

WDYT?

**Comment by fcamblor** [comment]
Considering Option 1, I'd maintain it shouldn't be restx console code responsibility to encode such path parameters ... angular, or even the browser should be more responsible on this regard.
So, I would keep a772376

That being said, I understand that restx should be able to decode URI PATH params, and I agree with you, if we change such important behaviour, we must be able to make this change widely (and easily)

However, my concern is the same as https://github.com/restx/restx/pull/262#discussion_r135490787 : if we provide a dedicated `HttpSettings` `@SettingsKey(key = "restx.http.decodeURLPathParams", defaultValue="true")`, then, how should we retrieve it into `StdRestxRequestMatcher` ?
Should we pass the `HttpSettings` to `StdRestxRequestMatcher` constructors (and thus, callers), or should we get `HttpSettings` from a static call to the `Factory` ?

WDYT ?

**Comment by xhanin** [comment]
I think this should go in `HttpServletRestxRequest`, because at the API level all calls to `RestxRequest` methods should provide decoded values (considering that the encoding is an implementation detail). And because `HttpServletRestxRequest` already has `HttpSettings` this is easy to have the proper settings.

WDYT?
