### ISSUE TITLE
Test Cases fail on windows due to line feed issues

### ISSUE THREAD

**Issue by samgabriel** [restx/restx#301]
Windows test cases fail due to line feed issues.

**Comment by samgabriel** [comment]
@fcamblor per your request new pull request was created.

**Comment by fcamblor** [comment]
I created 2 different PR for this :
- #304 which is in the same spirit of your PR #302, I mean : replacing hardcoded `\n` in RestX code base by `System.lineEnding()` in order to having mixing `\n` and `\r\n` in generated content
- #305 which takes the opposite idea, and prefer straightening platform-specific `\r\n` by single `\n`, meaning that we will consistently have `\n` in RestX generated content, no matter the platform where we're running

Former is avoiding breaking changes, but I feel the latter is a better approach in terms of consistency.

I would personally 👍 on #305 but will let other commiters (ping @xhanin @a-peyrard) or yourself @samgabriel raise any concern on it.

If no concern is raised until May 19th, I will merge #305

**Comment by fcamblor** [comment]
merged #305 which should fix this issue
